import { Room } from 'entity/checklist';

const rooms: Room[] = [
  {
    name: '1번째 방이름',
    cost: '월세 500/55',
    location: '서울특별시 관악구 봉천동',
    form: '원룸(주방 분리형(1.5룸))',
    size: '26.4㎡',
    floor: '3층 / 5층',
    elevator: '있음',
    expenses: '5만 원',
    active: true,
    checklist: [
      { type: 'check', label: '건물/방 상태', description: '연식이 5년 이하인가요?', value: true },
      {
        type: 'check',
        label: '건물/방 상태',
        description: '벽 모퉁이에 곰팡이가 없나요?',
        value: true,
      },
      {
        type: 'check',
        label: '옵션',
        description: '옵션의 상태, 파손은 없었나요?',
        value: true,
      },
      {
        type: 'check',
        label: '옵션',
        description: '도배를 새로 해주나요?',
        value: true,
      },
      {
        type: 'select',
        label: '방 정보',
        description: '관리비 포함 내역',
        value: [
          { name: '가스', selected: true },
          { name: '전기', selected: false },
          { name: '수도', selected: true },
          { name: '청소', selected: false },
          { name: '인터넷', selected: true },
          { name: 'TV', selected: false },
        ],
      },
    ],
  },
  {
    name: '2번째 방이름',
    cost: '월세 1000/65',
    location: '경기도 분당구 서현동',
    form: '원룸(주방 분리형(1.5룸))',
    size: '26.4㎡',
    floor: '3층 / 5층',
    elevator: '있음',
    expenses: '5만 원',
    active: false,
    checklist: [
      { type: 'check', label: '건물/방 상태', description: '연식이 5년 이하인가요?', value: false },
      {
        type: 'check',
        label: '건물/방 상태',
        description: '벽 모퉁이에 곰팡이가 없나요?',
        value: true,
      },
      {
        type: 'check',
        label: '옵션',
        description: '옵션의 상태, 파손은 없었나요?',
        value: false,
      },
      {
        type: 'check',
        label: '옵션',
        description: '도배를 새로 해주나요?',
        value: true,
      },
      {
        type: 'select',
        label: '방 정보',
        description: '관리비 포함 내역',
        value: [
          { name: '가스', selected: true },
          { name: '전기', selected: false },
          { name: '수도', selected: false },
          { name: '청소', selected: false },
          { name: '인터넷', selected: false },
          { name: 'TV', selected: false },
        ],
      },
    ],
  },

  {
    name: '3번째 방이름',
    cost: '월세 700/35',
    location: '경기도 광역시 판교',
    form: '원룸(주방 분리형(1.5룸))',
    size: '21.4㎡',
    floor: '2층 / 4층',
    elevator: '있음',
    expenses: '10만 원',
    active: false,
    checklist: [
      { type: 'check', label: '건물/방 상태', description: '연식이 5년 이하인가요?', value: true },
      {
        type: 'check',
        label: '건물/방 상태',
        description: '벽 모퉁이에 곰팡이가 없나요?',
        value: true,
      },
      {
        type: 'check',
        label: '옵션',
        description: '옵션의 상태, 파손은 없었나요?',
        value: false,
      },
      {
        type: 'check',
        label: '옵션',
        description: '도배를 새로 해주나요?',
        value: true,
      },
      {
        type: 'select',
        label: '방 정보',
        description: '관리비 포함 내역',
        value: [
          { name: '가스', selected: false },
          { name: '전기', selected: false },
          { name: '수도', selected: false },
          { name: '청소', selected: false },
          { name: '인터넷', selected: true },
          { name: 'TV', selected: false },
        ],
      },
    ],
  },

  {
    name: '4번째 방이름',
    cost: '월세 500/55',
    location: '서울특별시 동작구 7번 출구',
    form: '원룸(투룸))',
    size: '32.4㎡',
    floor: '1층',
    elevator: '있음',
    expenses: '15만 원',
    active: false,
    checklist: [
      { type: 'check', label: '건물/방 상태', description: '연식이 5년 이하인가요?', value: false },
      {
        type: 'check',
        label: '건물/방 상태',
        description: '벽 모퉁이에 곰팡이가 없나요?',
        value: true,
      },
      {
        type: 'check',
        label: '옵션',
        description: '옵션의 상태, 파손은 없었나요?',
        value: false,
      },
      {
        type: 'check',
        label: '옵션',
        description: '도배를 새로 해주나요?',
        value: true,
      },
      {
        type: 'select',
        label: '방 정보',
        description: '관리비 포함 내역',
        value: [
          { name: '가스', selected: true },
          { name: '전기', selected: false },
          { name: '수도', selected: false },
          { name: '청소', selected: false },
          { name: '인터넷', selected: false },
          { name: 'TV', selected: false },
        ],
      },
    ],
  },

  {
    name: '5번째 방이름',
    cost: '월세 500/55',
    location: '서울특별시 강남',
    form: '원룸(주방 분리형(1.5룸))',
    size: '52.4㎡',
    floor: '1층 / 2층 / 3층',
    elevator: '있음',
    expenses: '20만 원',
    active: false,
    checklist: [
      { type: 'check', label: '건물/방 상태', description: '연식이 5년 이하인가요?', value: false },
      {
        type: 'check',
        label: '건물/방 상태',
        description: '벽 모퉁이에 곰팡이가 없나요?',
        value: true,
      },
      {
        type: 'check',
        label: '옵션',
        description: '옵션의 상태, 파손은 없었나요?',
        value: false,
      },
      {
        type: 'check',
        label: '옵션',
        description: '도배를 새로 해주나요?',
        value: true,
      },
      {
        type: 'select',
        label: '방 정보',
        description: '관리비 포함 내역',
        value: [
          { name: '가스', selected: true },
          { name: '전기', selected: false },
          { name: '수도', selected: false },
          { name: '청소', selected: false },
          { name: '인터넷', selected: false },
          { name: 'TV', selected: false },
        ],
      },
    ],
  },

  {
    name: '6번째 방이름',
    cost: '월세 500/55',
    location: '서울특별시 관악구 봉천동',
    form: '원룸(주방 분리형(1.5룸))',
    size: '26.4㎡',
    floor: '3층 / 5층',
    elevator: '있음',
    expenses: '5만 원',
    active: false,
    checklist: [
      { type: 'check', label: '건물/방 상태', description: '연식이 5년 이하인가요?', value: false },
      {
        type: 'check',
        label: '건물/방 상태',
        description: '벽 모퉁이에 곰팡이가 없나요?',
        value: true,
      },
      {
        type: 'check',
        label: '옵션',
        description: '옵션의 상태, 파손은 없었나요?',
        value: false,
      },
      {
        type: 'check',
        label: '옵션',
        description: '도배를 새로 해주나요?',
        value: true,
      },
      {
        type: 'select',
        label: '방 정보',
        description: '관리비 포함 내역',
        value: [
          { name: '가스', selected: true },
          { name: '전기', selected: false },
          { name: '수도', selected: false },
          { name: '청소', selected: false },
          { name: '인터넷', selected: false },
          { name: 'TV', selected: false },
        ],
      },
    ],
  },
];

export default rooms;
